apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-rtmp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
        - name: nginx-rtmp
          image: viniciusccarvalho/docker-nginx-rtmp-1
          ports:
            - containerPort: 80
              name: http
            - containerPort: 1935
              name: rtmp
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-rtmp
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 1935
      name: rtmp
